# Generated by Django 3.1.2 on 2023-04-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20230405_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
